find_program(CCACHE_FOUND ccache)
if(CCACHE_FOUND)
    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
    set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
else()
    message(FATAL_ERROR "ERROR: ccache not found. Please, sudo apt-get install ccache")
endif(CCACHE_FOUND)
