# Настройка платформы сборки

if(WIN32)
	message("Windows platform")
	add_compile_options(-DWINDOWS)
	# Разрядность арзитектуры, бит
	if (CMAKE_SIZEOF_VOID_P EQUAL 8)
		set(ARCH_DIR "64-bit")
	elseif (CMAKE_SIZEOF_VOID_P EQUAL 4)
		set(ARCH_DIR "32-bit")
	else()
		message(FATAL_ERROR "Unsupported architecture, CMake will exit")
	endif()
	message("ARCH_DIR: " ${ARCH_DIR})
elseif(UNIX AND NOT APPLE)
	message("LINUX platform")
	add_compile_options(-DLINUX)
	# Разрядность арзитектуры, бит
	if (CMAKE_SIZEOF_VOID_P EQUAL 8)
		set(ARCH_DIR "64-bit")
	elseif (CMAKE_SIZEOF_VOID_P EQUAL 4)
		set(ARCH_DIR "32-bit")
	else()
		message(FATAL_ERROR "Unsupported architecture, CMake will exit")
	endif()
	message("ARCH_DIR: " ${ARCH_DIR})
else()
	message(FATAL_ERROR "Unsupported platform")
endif()
